In [46]:
import numpy as np
from numpy.random import randn
from numpy import tanh

# Dataset

In [14]:
train_data = {
  'good': True,
  'bad': False,
  'happy': True,
  'sad': False,
  'not good': False,
  'not bad': True,
  'not happy': False,
  'not sad': True,
  'very good': True,
  'very bad': False,
  'very happy': True,
  'very sad': False,
  'i am happy': True,
  'this is good': True,
  'i am bad': False,
  'this is bad': False,
  'i am sad': False,
  'this is sad': False,
  'i am not happy': False,
  'this is not good': False,
  'i am not bad': True,
  'this is not sad': True,
  'i am very happy': True,
  'this is very good': True,
  'i am very bad': False,
  'this is very sad': False,
  'this is very happy': True,
  'i am good not bad': True,
  'this is good not bad': True,
  'i am bad not good': False,
  'i am good and happy': True,
  'this is not good and not happy': False,
  'i am not at all good': False,
  'i am not at all bad': True,
  'i am not at all happy': False,
  'this is not at all sad': True,
  'this is not at all happy': False,
  'i am good right now': True,
  'i am bad right now': False,
  'this is bad right now': False,
  'i am sad right now': False,
  'i was good earlier': True,
  'i was happy earlier': True,
  'i was bad earlier': False,
  'i was sad earlier': False,
  'i am very bad right now': False,
  'this is very good right now': True,
  'this is very sad right now': False,
  'this was bad earlier': False,
  'this was very good earlier': True,
  'this was very bad earlier': False,
  'this was very happy earlier': True,
  'this was very sad earlier': False,
  'i was good and not bad earlier': True,
  'i was not good and not happy earlier': False,
  'i am not at all bad or sad right now': True,
  'i am not at all good or happy right now': False,
  'this was not happy and not good earlier': False,
}

test_data = {
  'this is happy': True,
  'i am good': True,
  'this is not happy': False,
  'i am not good': False,
  'this is not bad': True,
  'i am not sad': True,
  'i am very good': True,
  'this is very bad': False,
  'i am very sad': False,
  'this is bad not good': False,
  'this is good and happy': True,
  'i am not good and not happy': False,
  'i am not at all sad': True,
  'this is not at all good': False,
  'this is not at all bad': True,
  'this is good right now': True,
  'this is sad right now': False,
  'this is very bad right now': False,
  'this was good earlier': True,
  'i was not happy and not good earlier': False,
}

# Extract our vocabulary from our input space.

In [23]:
vocab = list(set([word for sentence in train_data.keys() for word in str(sentence).split(' ')]))


vocab_size = len(vocab)
f"The vocabulary size is {len(vocab)} and the first word is {vocab[0]}"

'The vocabulary size is 18 and the first word is good'

# Generate the one hot encoding of our vocabulary

In [16]:
word_to_idx = {word:index for index, word in enumerate(vocab)}
idx_to_word = {index:word for index, word in enumerate(vocab)}

word_to_idx, idx_to_word

({'good': 0,
  'am': 1,
  'right': 2,
  'sad': 3,
  'i': 4,
  'very': 5,
  'is': 6,
  'all': 7,
  'was': 8,
  'at': 9,
  'this': 10,
  'now': 11,
  'and': 12,
  'earlier': 13,
  'not': 14,
  'bad': 15,
  'or': 16,
  'happy': 17},
 {0: 'good',
  1: 'am',
  2: 'right',
  3: 'sad',
  4: 'i',
  5: 'very',
  6: 'is',
  7: 'all',
  8: 'was',
  9: 'at',
  10: 'this',
  11: 'now',
  12: 'and',
  13: 'earlier',
  14: 'not',
  15: 'bad',
  16: 'or',
  17: 'happy'})

In [39]:
def one_hot_encoding(text:str):
    input_data = []
    for word in text.lower().split(' '):
        word_one_hot = np.zeros((vocab_size, 1))
        word_one_hot[word_to_idx[word]] = 1
        input_data.append(word_one_hot)

    return input_data

In [32]:
one_hot_encoding('i am good')

[array([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])]

In [43]:
class RNN:

    def __init__(self, input_size, output_size, hidden_state=64):
        # h = (Wxh * Xt) +  (Whh * ht-1 ) + bh
        # y = Why * ht + by

        self.Wxh = randn(hidden_state, input_size) / 1000
        self.Whh = randn(hidden_state, hidden_state) / 1000
        self.Why = randn(output_size, hidden_state) / 1000

        self.bh = np.zeros((hidden_state, 1))
        self.by = np.zeros((output_size, 1))


    def forward(self, inputs):
        h = np.zeros((self.Whh.shape[0], 1))

        for i, x in enumerate(inputs):
            h = tanh(self.Wxh @ x + self.Whh @ h + self.bh)

            y = self.Why @ h + self.by

        return y, h        

In [44]:
def softmax(xs):
    return np.exp(xs) / sum(np.exp(xs))

In [55]:
rnn = RNN(vocab_size, 2)

inputs = one_hot_encoding("i am good")
out, h = rnn.forward(inputs)

probs = softmax(out)

probs

array([[0.5000004],
       [0.4999996]])